### ISSUE TITLE
Make the PGD web server on the kitchen instance accessible from the host machine

### ISSUE THREAD

**Issue by mathuin** [osuosl-cookbooks/pgd#15]
Some testing and development requires access to the web server running on the virtual machine instantiated by kitchen.  This will require modification of the Centos 6.6 platform definition in the kitchen YAML file to include a reference to an address in RFC1918 space under the driver config.  Here is an example:

```
platforms:
 - name: centos-6.6
   driver_config:
     username: vagrant
     image_ref: "Centos 6.6"
     network:
     - ["private network", {ip: "172.16.16.2", adapter: 2}]
```

With this change, a dev who is testing can connect to http://172.16.16.2/ and reasonably expect to see the PGD home page.

**Comment by ramereth** [comment]
Why aren't you using our openstack cluster?

**Comment by mathuin** [comment]
The pull request for that feature has not yet been rebased to master and then committed.

That being said, how will using openstack affect this issue?

**Comment by ramereth** [comment]
You wouldn't have to deal with this problem. Also the correct way to fix this for vagrant though is to foward a port using this method:

```
---
driver:
  name: vagrant
  network:
      - ["forwarded_port", {guest: 80, host: 8080}]
```

Then you just have to connect to port 8080 on localhost. I'd rather we do that instead of using private ip space.
